---
name: PR site preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed
    paths-ignore:
      - '.github/**'

concurrency:
  group: preview-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  build-site-preview:
    runs-on: ubuntu-latest
    name: Build site preview
    if: contains(fromJson('["opened", "reopened", "synchronize"]'), github.event.action)
    env:
      ELEVENTY_PATH_PREFIX: '/pr-previews/pr-${{ github.event.number }}/'
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install project modules
        run: npm ci

      - name: Build site 1st attempt
        continue-on-error: true
        id: firstBuild
        env:
          SITE_GITHUB_TOKEN: "${{ secrets.SITE_GITHUB_TOKEN }}"
        run: npm run build

      - name: Build site 2nd attempt
        if: steps.firstBuild.outcome == 'failure'
        env:
          SITE_GITHUB_TOKEN: "${{ secrets.SITE_GITHUB_TOKEN }}"
        run: npm run build

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Checkout pages branch
        run: git checkout gh-pages

      - name: Create preview target
        run: |
          mkdir -p pr-previews/pr-${{ github.event.number }}
          cp -rf _site/* pr-previews/pr-${{ github.event.number }}

      - name: Remove robots.txt from preview
        run: rm pr-previews/pr-${{ github.event.number }}/robots.txt

      - name: Count changed
        id: git_status
        run: |
            changedCount=$(git status pr-previews/pr-${{ github.event.number }} --porcelain=v1 --short --untracked-files=all | wc -l)
            echo "changedCount=$changedCount" >> "$GITHUB_OUTPUT"

      - name: Push preview target
        if: steps.git_status.outputs.changedCount > 0
        run: |
          git add pr-previews/pr-${{ github.event.number }}
          git commit -m "docs: deployed preview for pr #${{ github.event.number }}"
          git push origin gh-pages

      - name: Create a preview link
        if: steps.git_status.outputs.changedCount > 0
        id: pr_preview
        run: |
          cnameFile="CNAME"
          if [ -f "$cnameFile" ]; then
              cname=$(<$cnameFile)
              echo "link=https://$cname/pr-previews/pr-${{ github.event.number }}/" >> "$GITHUB_OUTPUT"
          else
              owner="${{ github.event.repository.owner.login }}"
              echo "link=https://$owner.github.io/pr-previews/pr-${{ github.event.number }}/" >> "$GITHUB_OUTPUT"
          fi

      - name: Comment with the preview link
        if: steps.git_status.outputs.changedCount > 0
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          header: site-preview
          message: |
            :rocket: Deployed site preview ${{ steps.pr_preview.outputs.link }}

            * will be up and ready in a couple of minutes.

  remove-site-preview:
    runs-on: ubuntu-latest
    name: Remove site preview
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Checkout pages branch
        run: git checkout gh-pages

      - name: Remove preview target
        continue-on-error: true
        run: |
          rm -r pr-previews/pr-${{ github.event.number }}
          git add pr-previews/pr-${{ github.event.number }}
          git commit -m "docs: removed preview for pr #${{ github.event.number }}"
          git push origin gh-pages

      - name: Remove the preview link comment
        uses: marocchino/sticky-pull-request-comment@v2.2.0
        with:
          header: site-preview
          delete: true
