---
name: PR site preview

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - closed

    # TODO: ADD EXCLUSIONS FOR UNRELATED SOURCES

concurrency: preview-${{ github.ref }}

jobs:
  build-site-preview:
    runs-on: ubuntu-latest
    name: Build site preview
    if: contains(fromJson('["opened", "reopened", "synchronize"]'), github.event.action)
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install project modules
        run: npm ci

      - name: Build site
        run: npm run build

      - name: Checkout pages branch
        run: git checkout gh-pages

      - name: Create preview target
        run: |
          mkdir -p docs/pr-previews/pr-${{ github.event.number }}
          cp -rf _site/* docs/pr-previews/pr-${{ github.event.number }}

      - name: Push preview target
        run: |
          git add docs/pr-previews/pr-${{ github.event.number }}
          git commit -m "docs: deployed preview for pr #${{ github.event.number }}"
          git push origin gh-pages

      # TODO: ADD/UPDATE STICKY COMMENT WITH TARGET URL

  remove-site-preview:
    runs-on: ubuntu-latest
    name: Remove site preview
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Checkout pages branch
        run: git checkout gh-pages

      - name: Remove preview target
        run: |
          rm -r docs/pr-previews/pr-${{ github.event.number }}
          git add docs/pr-previews/pr-${{ github.event.number }}
          git commit -m "docs: removed preview for pr #${{ github.event.number }}"
          git push origin gh-pages

      # TODO: UPDATE STICKY COMMENT WITH TARGET URL
