---
name: Stage

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  stage:
    runs-on: ubuntu-latest
    name: Stage the project
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install node 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm

      - name: Install project modules
        run: npm ci

      - name: Build site
        run: npm run build
